###############################################################
#                Authelia minimal configuration               #
###############################################################

port: 9091
tls_cert: /var/lib/authelia/ssl/cert.pem
tls_key: /var/lib/authelia/ssl/key.pem

log_level: debug

default_redirection_url: https://home.example.com:8080/

jwt_secret: unsecure_secret

authentication_backend:
  file:
    path: /var/lib/authelia/users.yml

session:
  secret: unsecure_session_secret
  domain: example.com
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  remember_me_duration: 1y

storage:
  local:
    path: /var/lib/authelia/db.sqlite

access_control:
  default_policy: deny
  rules:
    - domain: singlefactor.example.com
      policy: one_factor
    - domain: public.example.com
      policy: bypass
    - domain: home.example.com
      policy: bypass
    - domain: unsafe.local
      policy: bypass

notifier:
  smtp:
    host: smtp
    port: 1025
    sender: admin@example.com
    disable_require_tls: true