version: '3'
services:
  authelia-backend:
    image: authelia:dist
    labels:
      # Traefik 1.x
      - 'traefik.frontend.rule=Host:login.example.com;PathPrefix:/api'
      - 'traefik.protocol=https'
      # Traefik 2.x
      - 'traefik.http.routers.authelia_backend.rule=Host(`login.example.com`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.authelia_backend.entrypoints=https'
      - 'traefik.http.routers.authelia_backend.tls=true'
      - 'traefik.http.services.authelia-backend-authelia.loadbalancer.server.scheme=https'
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      authelianet:
        ipv4_address: 192.168.240.50