version: '3'
services:
  authelia-backend:
    environment:
      - AUTHELIA_JWT_SECRET=very_important_secret
      - AUTHELIA_SESSION_SECRET=unsecure_session_secret
    volumes:
      - './Standalone/configuration.yml:/etc/authelia/configuration.yml:ro'
      - './Standalone/users.yml:/var/lib/authelia/users.yml'
      - './common/ssl:/var/lib/authelia/ssl:ro'
      - '/tmp:/tmp'
    user: ${USER_ID}:${GROUP_ID}