###############################################################
#                Authelia minimal configuration               #
###############################################################

port: 9091
tls_cert: /var/lib/authelia/ssl/cert.pem
tls_key: /var/lib/authelia/ssl/key.pem

log_level: debug

jwt_secret: unsecure_secret

default_redirection_url: https://home.example.com:8080/

authentication_backend:
  file:
    path: /var/lib/authelia/users.yml

session:
  secret: unsecure_session_secret
  domain: example.com
  inactivity: 5
  expiration: 8
  remember_me_duration: 1y

storage:
  local:
    path: /var/lib/authelia/db.sqlite

totp:
  issuer: example.com

access_control:
  default_policy: deny

  rules:
    - domain: singlefactor.example.com
      policy: one_factor

    - domain: "*.example.com"
      subject: "group:admins"
      policy: two_factor

    - domain: dev.example.com
      resources:
        - "^/users/john/.*$"
      subject: "user:john"
      policy: two_factor

    - domain: dev.example.com
      resources:
        - "^/users/harry/.*$"
      subject: "user:harry"
      policy: two_factor

    - domain: "*.mail.example.com"
      subject: "user:bob"
      policy: two_factor

    - domain: dev.example.com
      resources:
        - "^/users/bob/.*$"
      subject: "user:bob"
      policy: two_factor

regulation:
  max_retries: 3
  find_time: 3
  ban_time: 5

notifier:
  smtp:
    host: smtp
    port: 1025
    sender: admin@example.com
    disable_require_tls: true